'btw, this project is purposefully not elegant at all, but rather how a beginner would write it 



'the following names are made from the computer, so that's why they're not very diverse, sorry :p


Print"########################################################################################################################"
Print"#                                                                                                                      #"
Print"#                                                                                                                      #"
Print"#                                                                                                                      #"
Print"#                                                                                                                      #"
Print"#                                                                                                                      #"
Print"#                                                                                                                      #"
Print"#                                                Welcome to BINARY!                                                    #"
Print"#                                                                                                                      #"
Print"#                                  Make sure there isn't much space outside of this box,                               #"
Print"#                                                                                                                      #"
Print"#                                          and that this box looks like a box.                                         #"
Print"#                                                                                                                      #"
Print"#                                                                                                                      #"
Print"#                                         Once that's done, press enter to start!                                      #"
Print"#                                   (I reccomend not changing for a little bit first)                                  #"
Print"#                                                                                                                      #"
Print"#                               btw, when you get asked a question, type either 'yes' or 'no'                          #"
Print"#                                                                                                                      #"
Print"#                                                                                                                      #"
Print"#                                                                                                                      #"
Print"#                                                                                                                      #"
Print"#                                                                                                                      #"
Print"#                                                                                                                      #"
Print"########################################################################################################################"
dim dummy as string
input "", dummy


Dim As String filename = "intro.txt"
Dim As Integer fileNumber = FreeFile()
Dim As String fileline
Dim As Integer i

' Open the file for input
Open filename For Input As #fileNumber
If Err Then
	Print "Error opening file: " & filename
	End
End If

' Read the file line by line

Do While Not Eof(fileNumber)
	Line Input #fileNumber, fileline
		If fileline = "^" Then
			Sleep(83,1)
		Else
			Print fileline
		End If
Loop



' Close the file
Close #fileNumber


s:

Dim Male_Names(20) as String
Male_Names(0) = "Robert"
Male_Names(1) = "John"
Male_Names(2) = "Michael"
Male_Names(3) = "Will"
Male_Names(4) = "David"
Male_Names(5) = "Richard"
Male_Names(6) = "Joseph"
Male_Names(7) = "Thomas"
Male_Names(8) = "Charles"
Male_Names(9) = "Christopher"
Male_Names(10) = "Daniel"
Male_Names(11) = "Matthew"
Male_Names(12) = "Anthony"
Male_Names(13) = "Donald"
Male_Names(14) = "Mark"
Male_Names(15) = "Paul"
Male_Names(16) = "Steven"
Male_Names(17) = "Andrew"
Male_Names(18) = "Kenneth"
Male_Names(19) = "Joshua"

Dim Male_Nicknames(20) as String
Male_Nicknames(0) = "Rob"
Male_Nicknames(1) = "Jonny"
Male_Nicknames(2) = "Mike"
Male_Nicknames(3) = "Will"
Male_Nicknames(4) = "Dave"
Male_Nicknames(5) = "Rich"
Male_Nicknames(6) = "Joe"
Male_Nicknames(7) = "Tom"
Male_Nicknames(8) = "Charlie"
Male_Nicknames(9) = "Chris"
Male_Nicknames(10) = "Dan"
Male_Nicknames(11) = "Matt" 
Male_Nicknames(12) = "Ant"
Male_Nicknames(13) = "Don"
Male_Nicknames(14) = "Mark"
Male_Nicknames(15) = "Paul"
Male_Nicknames(16) = "Steve"
Male_Nicknames(17) = "Andy"
Male_Nicknames(18) = "Ken"
Male_Nicknames(19) = "Josh"

Dim Female_Names(20) as String
Female_Names(0) = "Mary"
Female_Names(1) = "Hellena"
Female_Names(2) = "Lyra"
Female_Names(3) = "Alice"
Female_Names(4) = "Elizabeth"
Female_Names(5) = "Jennifer"
Female_Names(6) = "Maria"
Female_Names(7) = "Anna"
Female_Names(8) = "Becca"
Female_Names(9) = "Samantha"
Female_Names(10) = "Jessica"
Female_Names(11) = "Sarah"
Female_Names(12) = "Natalie"
Female_Names(13) = "Alexandra"
Female_Names(14) = "Linda"
Female_Names(15) = "Mia"
Female_Names(16) = "Grace"
Female_Names(17) = "Sophia"
Female_Names(18) = "Victoria"
Female_Names(19) = "Evelyn"

Dim Female_Nicknames(20) as String
Female_Nicknames(0) = "Mary"
Female_Nicknames(1) = "Helen"
Female_Nicknames(2) = "Lyra"
Female_Nicknames(3) = "Alice"
Female_Nicknames(4) = "Liz"
Female_Nicknames(5) = "Jen"
Female_Nicknames(6) = "Maria"
Female_Nicknames(7) = "Anna"
Female_Nicknames(8) = "Becky"
Female_Nicknames(9) = "Sam"
Female_Nicknames(10) = "Jess"
Female_Nicknames(11) = "Sarah"
Female_Nicknames(12) = "Nat"
Female_Nicknames(13) = "Alex"
Female_Nicknames(14) = "Linda"
Female_Nicknames(15) = "Mia"
Female_Nicknames(16) = "Grace"
Female_Nicknames(17) = "Soph"
Female_Nicknames(18) = "Victoria"
Female_Nicknames(19) = "Evelyn"

Dim Last_Names(20) as String
Last_Names(0) = "Smith"
Last_Names(1) = "Johnson"
Last_Names(2) = "Williams"
Last_Names(3) = "Jones"
Last_Names(4) = "Brown"
Last_Names(5) = "Davis"
Last_Names(6) = "Miller"
Last_Names(7) = "Wilson"
Last_Names(8) = "Moore"
Last_Names(9) = "Taylor"
Last_Names(10) = "Anderson"
Last_Names(11) = "Thomas"
Last_Names(12) = "Jackson"
Last_Names(13) = "White"
Last_Names(14) = "Harris"
Last_Names(15) = "Martin"
Last_Names(16) = "Thompson"
Last_Names(17) = "Garcia"
Last_Names(18) = "Martinez"
Last_Names(19) = "Robinson"

'we're using actual transfem names here now, this isn't just the author randomly picking ones that sound "right" 
'source: https://www.reddit.com/r/MtF/comments/sz2lkp/popularstereotypical_trans_women_names/
'am doing my best to do this in good faith :)

Dim Transfem_Names(20) as String
Transfem_Names(0) = "Lilly"
Transfem_Names(1) = "Lily"
Transfem_Names(2) = "Luna"
Transfem_Names(3) = "Kat"
Transfem_Names(4) = "Jade"
Transfem_Names(5) = "Rain"
Transfem_Names(6) = "Julia"
Transfem_Names(7) = "Caroline"
Transfem_Names(8) = "Chloe"
Transfem_Names(9) = "Winter"
Transfem_Names(10) = "Willow"
Transfem_Names(11) = "Emily"
Transfem_Names(12) = "Ruby"
Transfem_Names(13) = "Zoey"
Transfem_Names(14) = "Emma"
Transfem_Names(15) = "Alice"
Transfem_Names(16) = "Kara"
Transfem_Names(17) = "Artemis"
Transfem_Names(18) = "Sophie"
Transfem_Names(19) = "Lexii"

'same thing here as prev, lol 
'source: https://www.reddit.com/r/ftm/comments/zp3806/what_are_the_most_common_trans_masc_names/
Dim Transmasc_Names(20) as String
Transmasc_Names(0) = "Kai"
Transmasc_Names(1) = "Elliot"
Transmasc_Names(2) = "Oliver"
Transmasc_Names(3) = "Erza"
Transmasc_Names(4) = "Ari"
Transmasc_Names(5) = "Alex"
Transmasc_Names(6) = "Alec"
Transmasc_Names(7) = "Finn"
Transmasc_Names(8) = "Jona"
Transmasc_Names(9) = "Leo"
Transmasc_Names(10) = "Jay"
Transmasc_Names(11) = "Miles"
Transmasc_Names(12) = "Norman"
Transmasc_Names(13) = "Sam"
Transmasc_Names(14) = "Grayson"
Transmasc_Names(15) = "Vincent"
Transmasc_Names(16) = "Eli"
Transmasc_Names(17) = "Theo"
Transmasc_Names(18) = "Max"
Transmasc_Names(19) = "Skyler"



Dim AGAB as Integer 
Dim Given_Name as String
Dim Nickname as String
Dim Lastname as String
Dim NameIndex as Integer

Randomize, 1

AGAB = int(RND * 2)
'AGAB = 0
NameIndex = int(RND * 20)

If AGAB = 0 Then
	Given_Name = Male_Names(NameIndex)
	Nickname = Male_Nicknames(NameIndex)
	Lastname = Last_Names(int(RND * 20))

Else
	Given_Name = Female_Names(NameIndex)
	Nickname = Female_Nicknames(NameIndex)
	Lastname = Last_Names(int(RND * 20))
End If










Sleep 500

Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Dim randday as Integer
randday = int(RND * 10)

Dim given_genders(2) as String
given_genders(0) = "boy"
given_genders(1) = "girl"

Dim toadd as Integer
toadd = 118-57-len(given_genders(AGAB)) - len(Given_Name) - len(Lastname) - 3

'add space toadd times to toaddstr
Dim toaddstr as String
For i = 1 to toadd
	toaddstr = toaddstr & " "
Next i

Dim state as Integer
state = 1 + AGAB

Print "########################################################################################################################"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                    On July"; randday; ", 2002, you awaken, a "; given_genders(AGAB); " named "; Given_Name; " "; Lastname; "."; toaddstr; "#"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "########################################################################################################################"

Sleep 190

Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""

if AGAB = 0 Then

Print "########################################################################################################################"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                    On July"; randday; ", 2002, you awaken, a "; given_genders(AGAB); " named "; Given_Name; " "; Lastname; "."; toaddstr; "#"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "########################################################################################################################"

Sleep 183
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""


Print "########################################################################################################################"
Print "#    'Toughen up!'                                                                                                      #"
Print "#                                                                                                                       #"
Print "#                    On July"; randday; ", 2002, you awaken, a "; given_genders(AGAB); " named "; Given_Name; " "; Lastname; "."; toaddstr; "#"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                  'tha#"
Print "#n't cry'                                                                                                              #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#day'                                                                                                                  #"
Print "#                                                                                                                      #"
Print "#                                                                                                                'man u#"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "# g                                                                                                                    #"
Print "#n                                                                                                                 'boy#"
Print "########################################################################################################################"

Sleep 283
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""

Print "########################################################################################################################"
Print "#                                                          'don't be girly'                                            #"
Print "#     'Toughen up!'                                                                                                    #"
Print "#                    On July"; randday; ", 2002, you awaken, a "; given_genders(AGAB); " named "; Given_Name; " "; Lastname; "."; toaddstr; "#"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                             'that toy#"
Print "#    'boys don't cry'                                                                                                  #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                   'yo#"
Print "#day'                                                                                                                  #"
Print "#                                                                                                                      #"
Print "#                                                                                                            'man up!' #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#   g                                                                                                                  #"
Print "#  n                                                                                                                   #"
Print "# o                                                                                                                    #"
Print "#r                                                             'join the army'                                  'boys w#"
Print "########################################################################################################################"

Sleep 283
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""

Print "########################################################################################################################"
Print "#                                                                                                                      #"
Print "#                                                           'don't be girly'                                           #"
Print "#     'Toughen up!'  On July"; randday; ", 2002, you awaken, a "; given_genders(AGAB); " named "; Given_Name; " "; Lastname; "."; toaddstr; "#"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                        'that toy's fo#"
Print "#        'boys don't cry'                                                                                              #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                              'you're #"
Print "#some day'                                                                                                             #"
Print "#                                                                                                                      #"
Print "#                                                                                                            'man up!' #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#      g                                                                                                               #"
Print "#     n                                                                                                                #"
Print "#    o                                                                                                                 #"
Print "#   r                                                                                                                  #"
Print "#  t                                                                                                                   #"
Print "# s                                                                                                                    #"
Print "#                                                                  'join the army'                         'boys will be#"
Print "########################################################################################################################"

Sleep 283
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""

Print "########################################################################################################################"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                    On July"; randday; ", 2002, you awaken, a "; given_genders(AGAB); " named "; Given_Name; " "; Lastname; "."; toaddstr; "#"
Print "#             'Toughen up!'                                                                                            #"
Print "#                                                                                                                      #"
Print "#                                                                                                     'that toy's for g#"
Print "#                     'boys don't cry'                                                                                 #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#to be a man some day'                                                                                'you're a boy not#"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                    'man up!'         #"
Print "#                                                                                                                      #"
Print "#         ong'                                                                                                         #"
Print "#      str                                                                                                             #"
Print "#                                                                                                                      #"
Print "#    e                                                                                                                 #"
Print "#   b                                                                                                                  #"
Print "#                                                                                                                      #"
Print "# a                                                                    'join the army'               'boys will be boys#"
Print "#t                          'girls have cooties'                                                                       #"
Print "########################################################################################################################"

Sleep 283
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""

Print "########################################################################################################################"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                    On July"; randday; ", 2002, you awaken, a "; given_genders(AGAB); " named "; Given_Name; " "; Lastname; "."; toaddstr; "#"
Print "#                      'Toughen up!'                                                                                   #"
Print "#                                                           'don't be girly'                                           #"
Print "#                                                                                               'that toy's for girls' #"
Print "#                                   'boys don't cry'                                                                   #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#'you're going to be a man some day'                                                                                   #"
Print "#                                                                                            'you're a boy not anything#"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#             strong'                                                                                                  #"
Print "#          be                                                                                        'man up!'         #"
Print "#      tta                                                                                                             #"
Print "#     o                                                                                                                #"
Print "#    g                                                                                                                 #"
Print "#                                                                                                                      #"
Print "#  u                                                                  'join the army'                                  #"
Print "# o                    'girls have cooties'                                                       'boys will be boys'  #"
Print "#y                                                                                                                     #"
Print "########################################################################################################################"

Sleep 283
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""

Print "########################################################################################################################"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                    On July"; randday; ", 2002, you awaken, a "; given_genders(AGAB); " named "; Given_Name; " "; Lastname; "."; toaddstr; "#"
Print "#                      'Toughen up!'                                                                                   #"
Print "#                                                                                                                      #"
Print "#                                                                                           'that toy's for girls'     #"
Print "#                                                  'boys don't crybe girly                                             #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#   'you're going to be a man some day'                                                                                #"
Print "#                                                                                     'you're a boy not anything else' #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#             strong'                                                                                                  #"
Print "#           be                                                                                     'man up!'           #"
Print "#      gotta                                                                                                           #"
Print "#    you                                                                                                               #"
Print "#   '                                                                                                                  #"
Print "#                                                                      'join the army'                                 #"
Print "#                       'girls have cooties'                                                                           #"
Print "#                                                                                      'boys will be boys'             #"
Print "#                                                                                                                      #"
Print "########################################################################################################################"

Sleep 283
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""

Print "########################################################################################################################"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                    On July"; randday; ", 2002, you awaken, a "; given_genders(AGAB); " named "; Given_Name; " "; Lastname; "."; toaddstr; "#"
Print "#                        'Toughen up!'                                                                                 #"
Print "#                                                                                            'that toy's for girls'    #"
Print "#                                                                                                                      #"
Print "#                                                           'boys don't cry'                                           #"
Print "#                                                                                                                      #"
Print "#                                                         'don't be girly'                                             #"
Print "#                                                                                                                      #"
Print "#   'you're going to be a man some day'                                                                                #"
Print "#                                                                                  'you're a boy not anything else'    #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#              tta be strong'                                                                                          #"
Print "#            go                                                                                    'man up!'           #"
Print "#        'you                                                                                                          #"
Print "#                                                                                                                      #"
Print "#                                                                  'join the army'                                     #"
Print "#                                                                                                                      #"
Print "#                       'girls have cooties'                                                                           #"
Print "#                                                                                      'boys will be boys'             #"
Print "#                                                                                                                      #"
Print "########################################################################################################################"

Sleep 283
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""


Print "########################################################################################################################"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                    On July"; randday; ", 2002, you awaken, a "; given_genders(AGAB); " named "; Given_Name; " "; Lastname; "."; toaddstr; "#"
Print "#                                                                                          'that toy's for girls'      #"
Print "#                          'Toughen up!'                                                                               #"
Print "#                                                                                                                      #"
Print "#                                                               'boys don't cry'                                       #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#               'you're going to be a man some day'                                                                    #"
Print "#                                                                            'you're a boy, not anything else'         #"
Print "#                                                                                                                      #"
Print "#                                                         'don't be girly'                                             #"
Print "#                            'you gotta be strong'                                                                     #"
Print "#                                                                                                                      #"
Print "#                                                                                             'man up!'                #"
Print "#                                                                                                                      #"
Print "#                                                                   'join the army'                                    #"
Print "#                       'girls have cooties'                                                                           #"
Print "#                                                                                                                      #"
Print "#                                                                                     'boys will be boys'              #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "########################################################################################################################"

Sleep 9830

goto change 

Else


Print "########################################################################################################################"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                    On July"; randday; ", 2002, you awaken, a "; given_genders(AGAB); " named "; Given_Name; " "; Lastname; "."; toaddstr; "#"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "########################################################################################################################"

Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""

Print "########################################################################################################################"
Print "#          'you got to take care of the house someday'                                                                 #"
Print "#                                                                                                                      #"
Print "#                    On July"; randday; ", 2002, you awaken, a "; given_genders(AGAB); " named "; Given_Name; " "; Lastname; "."; toaddstr; "#"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#for boys'                                                                                                             #"
Print "#                                                                                                        'that's not pr#"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "# gross'                                                                                                        'you sme#"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                   'boys go to        #"
Print "#                                                                                                              jupiter #"
Print "#prim and proper'                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                             'Be pretty and smart'                                    #"
Print "########################################################################################################################"

Sleep 183
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""

Print "########################################################################################################################"
Print "#                                                                                                                      #"
Print "#                 'you got to take care of the house someday'                                                          #"
Print "#                    On July"; randday; ", 2002, you awaken, a "; given_genders(AGAB); " named "; Given_Name; " "; Lastname; "."; toaddstr; "#"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#'that toy's for boys'                                                                                                 #"
Print "#                                                                                                   'that's not proper #"
Print "#                                                                                                                      #"
Print "#                                                                                                       'you smell! fre#"
Print "#                                                                                                                      #"
Print "#  'boys are gross'                                                                                                    #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                         'boys go to                  #"
Print "#                                                                                                  jupiter to get      #"
Print "#                                                                                                              more stu#"
Print "#  'you should be prim and proper'                                                                                     #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                              'Be pretty and smart'                                   #"
Print "#                                                                                                                      #"
Print "########################################################################################################################"

Sleep 183
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""

Print "########################################################################################################################"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                    On July"; randday; ", 2002, you awaken, a "; given_genders(AGAB); " named "; Given_Name; " "; Lastname; "."; toaddstr; "#"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#  'that toy's for boys'                                                                                               #"
Print "#                                                                                  'that's not proper of a young lady' #"
Print "#                                                                                               'you smell! freshen up'#"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#          'boys are gross'                                                                                            #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                              'boys go to jupiter to get              #"
Print "#                                                                                                      more stupider'  #"
Print "#                                                                                                                      #"
Print "#  'you should be prim and proper'                                                                                     #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                              'Be pretty and smart'                                   #"
Print "#                                                                                                                      #"
Print "########################################################################################################################"

Sleep 183
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""

Print "########################################################################################################################"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                    On July"; randday; ", 2002, you awaken, a "; given_genders(AGAB); " named "; Given_Name; " "; Lastname; "."; toaddstr; "#"
Print "#                                                                                                                      #"
Print "#                                   'you got to take care of the house someday'                                        #"
Print "#                                                                                                                      #"
Print "#                                                                                      'you smell! freshen up'         #"
Print "#      'that toy's for boys'                                                                                           #"
Print "#                                                      'that's not proper of a young lady'                             #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                     'boys are gross'                                                                                 #"
Print "#                                                                                                                      #"
Print "#                                                              'boys go to jupiter to get more stupider'               #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#             'you should be prim and proper'                                                                          #"
Print "#                                                                                                                      #"
Print "#                                                           'Be pretty and smart'                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "########################################################################################################################"


Sleep 9830

goto change 
End If


change:

Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""


Print "########################################################################################################################"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                 |\       __          \    /    __     _    _         _     _   _____    ____   |    |                #"
Print "#                 | \     /  \          \  /    /  \    |    |         |     |     |     /       |    |                #"
Print "#                 |  \   |    |          \/    |    |   |    |         |     |     |     \       |____|                #"
Print "#                 |  /   |    |          ||    |    |   |    |         \     /     |      \___   |    |                #"
Print "#                 | /     \  /           ||     \  /    |    |          \ ^ /      |         /   |    |                #"
Print "#                 |/       --            ||      --      \__/            \ /     -----   ---/    |    |                #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "########################################################################################################################"

Sleep 183

Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""

Print "########################################################################################################################"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                 |\       __          \    /    __     _    _         _     _   _____    ____   |    |                #"
Print "#                 | \     /  \          \  /    /  \    |    |         |     |     |     /       |    |                #"
Print "#                 |  \   |    |          \/    |    |   |    |         |     |     |     \       |____|                #"
Print "#                 |  /   |    |          ||    |    |   |    |         \     /     |      \___   |    |                #"
Print "#                 | /     \  /           ||     \  /    |    |          \ ^ /      |         /   |    |                #"
Print "#                 |/       --            ||      --      \__/            \ /     -----   ---/    |    |                #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#              _____     __            ____   |    |       ^        |    |      ____    ._____     ___                 #"
Print "#                |      /  \          /   /   |    |      / \       |\   |     /   |    |         /   \                #"
Print "#                |     |    |        |        |____|     /___\      | \  |    |         |_____        /                #"
Print "#                |     |    |        |        |    |    /     \     |  \ |    |  |_     |            /                 #"
Print "#                |      \  /          \   \   |    |   /       \    |   \|     \   \    |           |                  #"
Print "#                |       --            ----   |    |  /         \   |    |      ----    |_____      o                  #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "########################################################################################################################"

dim ans as string
input "", ans

if ans = "yes"  then
	goto a
Elseif ans = "no"  then
	goto s
end if


a:
state = 5

Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""


Print "########################################################################################################################"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                       you realize                                                                    #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "########################################################################################################################"

Sleep 1183
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""



Print "########################################################################################################################"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                       you realize                                                                    #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                               that this box                                          #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "########################################################################################################################"

Sleep 1183
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""


Print "########################################################################################################################"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                       you realize                                                                    #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                               that this box                                          #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                 like any box                                                                         #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "########################################################################################################################"

Sleep 1183
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""



Print "########################################################################################################################"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                       you realize                                                                    #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                               that this box                                          #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                 like any box                                                                         #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                               is just a construct                                    #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "########################################################################################################################"

Sleep 1183
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""

Print "########################################################################################################################"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                     break out                                                                                        #"
Print "#                                                                           break out                                  #"
Print "#                                                                                                                      #"
Print "#                                       you realize                                          break out                 #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                               that this box                                          #"
Print "#                                                                                                                      #"
Print "#       break out                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                 like any box                                                 break out               #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "#                                                               is just a construct                                    #"
Print "#                                                                                               break out              #"
Print "#           break out                                                                                                  #"
Print "#                                                                                                                      #"
Print "#                                                break out                                                             #"
Print "#                                                                                                                      #"
Print "#                                                                                                                      #"
Print "########################################################################################################################"

Sleep 2183
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""




Print "     ##########################                             ############################################### "
Print "    ###                       ##                        ########                                         ####          " 
Print "   #                           ###        ###############                                                   ##         "
Print "  #               break out      ##########                              break out                           ###       "
Print "##                                                                                                             ###     "
Print "#                                                                                              break out         ###    "
Print "#                                       you realize                                                                ###  "
Print "#                                                                                                                   ####"
Print "#                                                                                                                     ##"
Print "#                                                               that this box                                          #"
Print "#                                                                                                                      #"
Print "##       break out                                                                                                     #"
Print "##                                                                                                                     #"
Print " ##                               like any box                                                                         #"
Print "  #                                                                                                                    #"
Print "  #                                                                                               break out            #"
Print "  ##                                                                                                                  ##"
Print "   #                                                            is just a construct                                  ###"
Print "   ##                                                                                                               ####"
Print "    #                                                                                                             ##### "
Print "    #     break out                                                                          break out        ########  "
Print "    ##                                                                                                    ########      "
Print "     ###                                         break out        ############                    ###########           "
Print "       #####          #############                           #######       ######    ################                  "
Print "          ##############         ################################              #############                            "

Sleep 2183
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""





Print "                                                                                                          # "
Print "          #                                            #                                                               " 
Print "                                                                                                                       "
Print "                  break out                                              break out                                     "
Print "                                                                                                                       "
Print "#                                                                                              break out                "
Print "                                        you realize                                                                #    "
Print "                                                                                                                        "
Print "                           #                                                                                            "
Print "                                                                that this box          #                                "
Print "                                                                                                             #          "
Print "         break out                               #                                                                      "
Print "                                                                                                                        "
Print "  #                               like any box                                                                          "
Print "                                                                               #                                        "
Print "                         #                                                                        break out             "
Print "                                                                                                                      # "
Print "   #                                                            is just a construct                                     "
Print "                                         #                                                                              "
Print "                                                                                                                        "
Print "          break out                                                                          break out                  "
Print "                                                                                                                        "
Print "      #                                          break out                                                              "
Print "                                                                                      #                                 "
Print "                                                                                                                        "

Sleep 2183
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""



Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""
Print ""


Print "Fin."
